### Signup - working
POST http://localhost:8000/api/auth/create/
Content-Type: application/json

{
    "password": "test1234", 
    "username": "test@example.com"
}

### Login - working
POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "password": "test1234", 
    "username": "test@example.com"
}

### Create new group - implemented
POST http://localhost:8000/api/group/create/
Content-Type: application/json
Authorization: Token b07fb01acd8d8a19da119469d4109c89e2182f32c1b31b25b6a1f075d6d3cf5a

{
    "name": "fo2e2",
    "description": "bar"
    
}

### Get group info -  implemented
# TODO non-sequential ids
GET http://localhost:8000/api/group/get-info?id=1
Content-Type: application/json
Authorization: Token b07fb01acd8d8a19da119469d4109c89e2182f32c1b31b25b6a1f075d6d3cf5a

### Set group info (name, description) - implemented
PUT http://localhost:8000/api/group/set-info?id=1
Content-Type: application/json
Authorization: Token b07fb01acd8d8a19da119469d4109c89e2182f32c1b31b25b6a1f075d6d3cf5a

{
    "name": "foo_updated_v2",
    "description": "foobar"
}

### Join group -implemented
PUT http://localhost:8000/api/group/join?id=1
Content-Type: application/json
Authorization: Token b07fb01acd8d8a19da119469d4109c89e2182f32c1b31b25b6a1f075d6d3cf5a


### Leave group -  implemented 
# FIXME csrf problems 
DELETE  http://localhost:8000/api/group/leave?id=1
Content-Type: application/json
Authorization: Token b07fb01acd8d8a19da119469d4109c89e2182f32c1b31b25b6a1f075d6d3cf5a



### Submit leaderboard time - not implemented
# TODO implement submit leaderboard
POST http://localhost:8000/api/group/submit-time
Content-Type: application/json

{
    "token": "testtoken",
    "group_ids": ["testgroup1", "testgroup2", "testgroup3"],
}

### Get leaderboard - not implemented
# TODO implement get leaderboard
GET http://localhost:8000/api/group/leaderboard
Content-Type: application/json

{
    "token": "testtoken",
    "group_id": "testgroup1",
}







